---
title: "Fee Inventory"
subtitle: "ORC 3345.024(A)(1)"
params:
    year: "2023-24"
    file: "FY24_FI.csv"
    lms: "Canvas"
    bookstore: "Commodore Books and More"
    bookstorelink: "http://bookstore.lorainccc.edu/SiteText?id=55657"
df-print: paged
execute:
    echo: false
---

```{R}
#| include: false
library(tidyverse)
library(knitr)

fee_data <- read.csv(params$file) %>%
    # reformat names from the original HEI template (if necessary)
    rename_with(~str_to_title(gsub(".", "", .x, fixed = TRUE))) %>%
    rename("Mincredit" = "Minimumcredit") %>%
    rename("Maxcredit" = "Maximumcredit") %>%
    mutate(
        amt_fmt = scales::dollar(Feeamount),
        percreditnote = case_when(
            Percreditswitch == "Y" ~ "per credit",
            TRUE ~ ""
        )
    )
```

The tuition and fee figures listed here are for **academic year `r params$year`**.

## Instructional and General Fees

### In-County Residents

#### Semester tuition & fees: 13 to 18 credit hours

```{R}
lc_resident_tf <- fee_data %>%
    filter(
        Feecategorycode == "IN" | Feecategorycode == "GE", 
        Percreditswitch == "N"
        ) %>%
    arrange(-Feeamount)

kable(
    rbind(
        select(lc_resident_tf, c("Feetitle", "amt_fmt")),
        c(
            "**Total Tuition & Fees**", 
            paste0(
                "**",
                scales::dollar(sum(lc_resident_tf$Feeamount)),
                "**"
            )
        )
    ),
    align = "lr",
    col.names = c("Fee", "Amount")
    )
```

#### Per credit hour (1-12 credit hours and surcharge on 19+ credit hours)

```{R}
lc_resident_tf <- fee_data %>%
    filter(
        Feecategorycode == "IN" | Feecategorycode == "GE", 
        Percreditswitch == "Y",
        Mincredit == 1
        ) %>%
    arrange(-Feeamount)

kable(
    rbind(
        select(lc_resident_tf, c("Feetitle", "amt_fmt")),
        c(
            "**Total Tuition & Fees per credit hour**", 
            paste0(
                "**",
                scales::dollar(sum(lc_resident_tf$Feeamount)),
                "**"
            )
        )
    ),
    align = "lr",
    col.names = c("Fee", "Amount")
    )
```

{{< pagebreak >}}

### Out-of-County Residents

Out-of-County Residents pay a surcharge on top of the in-county tuition rate.

#### Semester tuition & fees: 13 to 18 credit hours

```{R}
oh_resident_tf <- fee_data %>%
    filter(
        Feecategorycode == "IN" | Feecategorycode == "GE" | Feecode == "OD", 
        Percreditswitch == "N"
        ) %>%
    arrange(-Feeamount)

kable(
    rbind(
        select(oh_resident_tf, c("Feetitle", "amt_fmt")),
        c(
            "**Total Tuition & Fees**", 
            paste0(
                "**",
                scales::dollar(sum(oh_resident_tf$Feeamount)),
                "**"
            )
        )
    ),
    align = "lr",
    col.names = c("Fee", "Amount")
    )
```

#### Per credit hour (1-12 credit hours and surcharge on 19+ credit hours)

```{R}
oh_resident_tf <- fee_data %>%
    filter(
        Feecategorycode == "IN" | Feecategorycode == "GE" | Feecode == "OD", 
        Percreditswitch == "Y",
        Mincredit == 1
        ) %>%
    arrange(-Feeamount)

kable(
    rbind(
        select(oh_resident_tf, c("Feetitle", "amt_fmt")),
        c(
            "**Total Tuition & Fees per credit hour**", 
            paste0(
                "**",
                scales::dollar(sum(oh_resident_tf$Feeamount)),
                "**"
            )
        )
    ),
    align = "lr",
    col.names = c("Fee", "Amount")
    )
```

### Out-of-State Residents

Out-of-State Residents pay a surcharge on top of the in-county tuition rate.

#### Semester tuition & fees: 13 to 18 credit hours

```{R}
non_resident_tf <- fee_data %>%
    filter(
        Feecategorycode == "IN" | Feecategorycode == "GE" | Feecode == "OS", 
        Percreditswitch == "N"
        ) %>%
    arrange(-Feeamount)

kable(
    rbind(
        select(non_resident_tf, c("Feetitle", "amt_fmt")),
        c(
            "**Total Tuition & Fees**", 
            paste0(
                "**",
                scales::dollar(sum(non_resident_tf$Feeamount)),
                "**"
            )
        )
    ),
    align = "lr",
    col.names = c("Fee", "Amount")
    )
```

#### Per credit hour (1-12 credit hours and surcharge on 19+ credit hours)

```{R}
non_resident_tf <- fee_data %>%
    filter(
        Feecategorycode == "IN" | Feecategorycode == "GE" | Feecode == "OS", 
        Percreditswitch == "Y",
        Mincredit == 1
        ) %>%
    arrange(-Feeamount)

kable(
    rbind(
        select(non_resident_tf, c("Feetitle", "amt_fmt")),
        c(
            "**Total Tuition & Fees per credit hour**", 
            paste0(
                "**",
                scales::dollar(sum(non_resident_tf$Feeamount)),
                "**"
            )
        )
    ),
    align = "lr",
    col.names = c("Fee", "Amount")
    )
```

{{< pagebreak >}}

## Program Fees

Program fees are required of all students in an academic program, to provide a service or benefit.

```{R}
fee_data %>%
    filter(Feecategorycode == "SP", Feecode == "PF") %>%
    select(c("Academicprogram", "Feetitle", "amt_fmt")) %>%
    kable(
        align = "llr",
        col.names = c("Curriculum Code", "Fee", "Amount")
    )
```

## Special Purpose Fees

Special purpose fees apply to particular services or benefits provided to specific students and are not applied to all enrolled students.  Special purpose fees include fines.

```{R}
fee_data %>%
    filter(Feecategorycode == "SP", Feecode == "FI" | Feecode == "RB") %>%
    select(c("Feetitle", "amt_fmt")) %>%
    kable(
        align = "lr",
        col.names = c("Fee", "Amount")
    )
```

{{< pagebreak >}}

## Class Fees

Class fees apply to particular courses, typically to pay for equipment and materials used in the class, such as during laboratories or demonstrations.

```{R}
fee_data %>%
    filter(Feecategorycode == "SP", Feecode == "CF" | Feecode == "LB") %>%
    select(c("Courseid", "Feetitle", "amt_fmt", "percreditnote")) %>%
    arrange(Courseid) %>%
    kable(
        align = "llrl",
        col.names = c("Course", "Fee", "Amount", "Note")
    )
```

{{< pagebreak >}}

## Instant Access / Inclusive Access

Instant Access provides required course materials, such as eBooks or courseware, automatically through the `r params$lms` course portal.  The Ohio Department of Higher Education (ODHE) calls this Inclusive Access.  For more information, please see [`r params$bookstore`](`r params$bookstorelink`).

```{R}
fee_data %>%
    filter(Feecategorycode == "SP", Feecode == "IA") %>%
    select(c("Courseid", "Feetitle", "amt_fmt")) %>%
    kable(
        align = "llr",
        col.names = c("Course", "Material", "Amount")
    )
```